# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: Cache@2  # Not required, but Qodana will open projects with cache faster.
  inputs:
    key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
    path: '$(Agent.TempDirectory)/qodana/cache'
    restoreKeys: |
      "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
      "$(Build.Repository.Name)"